-- Dump of imapsync_db
-- Generated by Python Script


-- Table: jobs
DROP TABLE IF EXISTS `jobs`;
CREATE TABLE `jobs` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `source_host` varchar(255) DEFAULT NULL,
  `source_port` int DEFAULT NULL,
  `source_security` varchar(50) DEFAULT NULL,
  `target_host` varchar(255) DEFAULT NULL,
  `target_port` int DEFAULT NULL,
  `target_security` varchar(50) DEFAULT NULL,
  `options` text,
  `csv_path` varchar(500) DEFAULT NULL,
  `total_mailboxes` int DEFAULT NULL,
  `completed` int DEFAULT NULL,
  `failed` int DEFAULT NULL,
  `data_transferred` int DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_jobs_id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- Table: mailboxes
DROP TABLE IF EXISTS `mailboxes`;
CREATE TABLE `mailboxes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `job_id` varchar(36) DEFAULT NULL,
  `source_user` varchar(255) DEFAULT NULL,
  `source_pass` varchar(500) DEFAULT NULL,
  `target_user` varchar(255) DEFAULT NULL,
  `target_pass` varchar(500) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `message` text,
  `data_transferred` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `job_id` (`job_id`),
  KEY `ix_mailboxes_id` (`id`),
  CONSTRAINT `mailboxes_ibfk_1` FOREIGN KEY (`job_id`) REFERENCES `jobs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- Table: users
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(100) DEFAULT NULL,
  `hashed_password` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_users_username` (`username`),
  KEY `ix_users_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `users` VALUES 
(1, 'phongdh', '$2b$12$mmpgKE..mryai0GQEZGMDOnjUZunbXEnhcZX/DQsJ6gkzNDNFL.3.');
